name: Build

on:
  push:
    branches:
      - master
  pull_request:

env:
  DYN_NAME: flx_rs_core

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ext: so
          - os: macos-latest
            ext: dylib
          - os: windows-latest
            ext: dll
    steps:
      - uses: actions/checkout@v2

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Install LLVM and Clang (Unix)
        if: runner.os != 'Windows'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"

      - name: Install LLVM and Clang (Windows)
        if: runner.os == 'Windows'
        run: .github/script/setup-llvm

      - name: Build binaries
        run: |
          cd core
          cargo build --release

      - name: Upload binaries
        if: runner.os != 'Windows'
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.DYN_NAME }}.${{ matrix.ext }}
          path: core/target/release/lib${{ env.DYN_NAME }}.${{ matrix.ext }}

      - name: Upload binaries
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.DYN_NAME }}.${{ matrix.ext }}
          path: core/target/release/${{ env.DYN_NAME }}.${{ matrix.ext }}
